### ISSUE TITLE
Does this support slice?

### ISSUE THREAD

**Issue by coopci** [mdaverde/jsonpath#1]
slice like [,],
I tried this:

func must(err error) {
	return
}
func main() {
	sample := `{ "owner": { "name": "john doe", "contact": { "phone": "555-555-5555" }, "arr1": ["ele1", "ele2", "ele3"] } }`

	var payload interface{}

	err := json.Unmarshal([]byte(sample), &payload)
	must(err)

	ele1, err := jsonpath.Get(payload, "owner.arr1[0,1]")
	must(err)
	fmt.Printf("ele1: %s \n", ele1)
}

And it prints ele1: %!s(<nil>).
And I found jasonpath.go line54 calls strconv.Atoi(token) to parse token.

**Comment by mdaverde** [comment]
This does not support slice currently. Work needs to be done to add more of the JSONPath spec
